spring:
  datasource:
    username: root
    password: 1234560
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/map?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
  messages:
    basename: i18n.login
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd
    hiddenmethod:
      filter:
        enabled: true
#    schema:
#      - classpath:map.sql
server:
  port: 8080
  servlet:
    context-path: /
logging:
  file:
    name: ./logs/background.log
  level:
    com.wuhe: debug


